[project]
name = "supportsage"
version = "0.1.0"
description = ""
authors = [
    {name = "vsh0711",email = "vishalini2199@gmail.com"}
]
requires-python = ">=3.10,<3.15"
dependencies = [
    "datasets (>=5.0.0,<6.0.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)",
    "rank-bm25 (>=0.2.2,<0.3.0)",
    "pinecone (>=6.0.0,<7.0.0)",
    "sentence-transformers (>=3.0.0,<4.0.0)",
    "langchain-groq (>=0.1.0,<1.0.0)",
    "presidio-analyzer (>=2.2.30,<3.0.0)",
    "presidio-anonymizer (>=2.2.36)"
]



[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]
